"""Regenerate ``MODELS.md`` from the YAML frontmatter of every ``model.md``.

Walks ``models/<family>/<slug>/model.md``, parses each YAML header, and
writes a sortable markdown table to ``MODELS.md`` at the repo root.

Run after adding or updating a model:

    uv run python scripts/regenerate_models_index.py

Discovery logic lives in :mod:`tradinglib.models_index`; this script only
owns the markdown rendering.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from tradinglib.data.paths import repo_root
from tradinglib.models_index import find_models

HEADER = (
    "<!-- AUTO-GENERATED by scripts/regenerate_models_index.py — do not edit by hand -->\n"
    "\n"
    "# Models index\n"
    "\n"
    "| Name | Family | Window | Assets | Data sources | Sharpe (OOS) | Max DD | Status |\n"
    "| --- | --- | --- | --- | --- | --- | --- | --- |\n"
)

EMPTY_BODY = "\n_No models yet. Add one under `models/<family>/NN-slug/` with a `model.md` file._\n"


def fmt(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, list):
        return ", ".join(str(x) for x in value)
    if isinstance(value, float):
        return f"{value:.2f}"
    return str(value)


def row_to_markdown(meta: dict[str, Any]) -> str:
    name = meta.get("name", "?")
    path = meta["_path"]
    return (
        "| "
        + " | ".join(
            [
                f"[{name}]({path}/)",
                fmt(meta.get("family")),
                fmt(meta.get("window")),
                fmt(meta.get("assets")),
                fmt(meta.get("data_sources")),
                fmt(meta.get("sharpe_oos")),
                fmt(meta.get("max_drawdown")),
                fmt(meta.get("status")),
            ]
        )
        + " |"
    )


def render(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return HEADER + EMPTY_BODY
    body = "\n".join(row_to_markdown(r) for r in rows) + "\n"
    return HEADER + body


def main() -> None:
    rows = find_models(repo_root() / "models")
    out = repo_root() / "MODELS.md"
    out.write_text(render(rows), encoding="utf-8")
    print(f"Wrote {len(rows)} model(s) to {out}")


if __name__ == "__main__":
    main()
