"""Regenerate ``MODELS.md`` from the YAML frontmatter of every ``model.md``.

Walks ``models/<family>/<slug>/model.md``, parses each YAML header, and
writes a sortable markdown table to ``MODELS.md`` at the repo root.

Run after adding or updating a model:

    uv run python scripts/regenerate_models_index.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from tradinglib.data.paths import repo_root

HEADER = (
    "<!-- AUTO-GENERATED by scripts/regenerate_models_index.py — do not edit by hand -->\n"
    "\n"
    "# Models index\n"
    "\n"
    "| Name | Family | Window | Assets | Data sources | Sharpe (OOS) | Max DD | Status |\n"
    "| --- | --- | --- | --- | --- | --- | --- | --- |\n"
)

EMPTY_BODY = "\n_No models yet. Add one under `models/<family>/NN-slug/` with a `model.md` file._\n"


def parse_frontmatter(path: Path) -> dict[str, Any] | None:
    """Return the YAML frontmatter block at the top of a model.md file, or None."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 4)
    if end == -1:
        return None
    data = yaml.safe_load(text[4:end])
    return data if isinstance(data, dict) else None


def find_models(models_root: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for model_md in sorted(models_root.rglob("model.md")):
        meta = parse_frontmatter(model_md)
        if meta is None:
            continue
        meta["_path"] = model_md.parent.relative_to(repo_root()).as_posix()
        rows.append(meta)
    return rows


def fmt(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, list):
        return ", ".join(str(x) for x in value)
    if isinstance(value, float):
        return f"{value:.2f}"
    return str(value)


def row_to_markdown(meta: dict[str, Any]) -> str:
    name = meta.get("name", "?")
    path = meta["_path"]
    return (
        "| "
        + " | ".join(
            [
                f"[{name}]({path}/)",
                fmt(meta.get("family")),
                fmt(meta.get("window")),
                fmt(meta.get("assets")),
                fmt(meta.get("data_sources")),
                fmt(meta.get("sharpe_oos")),
                fmt(meta.get("max_drawdown")),
                fmt(meta.get("status")),
            ]
        )
        + " |"
    )


def render(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return HEADER + EMPTY_BODY
    body = "\n".join(row_to_markdown(r) for r in rows) + "\n"
    return HEADER + body


def main() -> None:
    root = repo_root()
    rows = find_models(root / "models")
    out = root / "MODELS.md"
    out.write_text(render(rows), encoding="utf-8")
    print(f"Wrote {len(rows)} model(s) to {out}")


if __name__ == "__main__":
    main()
